version: '3.7'
services:
    rpidrone:
        build: .
        privileged: true
        ports: 
            - "${SOCKET_PORT}:${SOCKET_PORT}"
        volumes: 
            - '/dev/ttyAMA0:/dev/ttyAMA0'
            - '/dev/mem:/dev/mem'